# Generated by Django 4.1.3 on 2022-11-16 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=25, unique=True, verbose_name='カテゴリー')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='食材名')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='賞味期限')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='消費期限')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_app.category', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
                'db_table': 'food',
            },
        ),
    ]
